/**
 * Curriculum skeleton for the Tuition Centre platform.
 *
 * This is a *curated skeleton* — the topic + subtopic structure grounded in the
 * UK National Curriculum (KS2/KS3) and exam-board specifications (GCSE/A-Level).
 * All teaching material, questions, and step-by-step solutions are generated by
 * the AI engine on demand (see /api/tutor-lesson and /api/tutor-worksheet).
 *
 * Coverage: Year 3 → A-Level, subjects Maths / English / Science.
 * Exam boards are surfaced on GCSE and A-Level, where they matter.
 */

import { MATHS_SEEDS } from "./maths";
import { ENGLISH_SEEDS } from "./english";
import { SCIENCE_SEEDS } from "./science";

export type CurriculumSubjectId = "maths" | "english" | "science";

export type CurriculumStageId =
  | "year-3"
  | "year-4"
  | "year-5"
  | "year-6"
  | "year-7"
  | "year-8"
  | "year-9"
  | "gcse"
  | "a-level";

export type KeyStage = "KS2" | "KS3" | "KS4" | "KS5";

export type ExamBoardId = "AQA" | "Edexcel" | "OCR" | "WJEC" | "Eduqas";

export interface CurriculumStage {
  id: CurriculumStageId;
  label: string; // "Year 3", "GCSE"
  shortLabel: string; // "Y3", "GCSE"
  keyStage: KeyStage;
  ages: string; // "Age 7–8"
  hasExamBoards: boolean;
  order: number;
  blurb: string;
}

export interface CurriculumSubject {
  id: CurriculumSubjectId;
  name: string;
  emoji: string;
  color: string; // tailwind gradient-ish accent
}

export interface CurriculumTopic {
  id: string; // globally unique, stable
  stageId: CurriculumStageId;
  subjectId: CurriculumSubjectId;
  strand: string; // e.g. "Number", "Reading", "Biology"
  name: string;
  subtopics: string[];
  /** When set, this topic is specific to these boards. Undefined = all boards. */
  examBoards?: ExamBoardId[];
}

/** A seed is the compact authoring format used inside the subject data files. */
export interface TopicSeed {
  strand: string;
  name: string;
  subtopics: string[];
  examBoards?: ExamBoardId[];
}

export type SubjectSeeds = Partial<Record<CurriculumStageId, TopicSeed[]>>;

// ── Stages ────────────────────────────────────────────────────────────────────

export const STAGES: CurriculumStage[] = [
  { id: "year-3", label: "Year 3", shortLabel: "Y3", keyStage: "KS2", ages: "Age 7–8", hasExamBoards: false, order: 3, blurb: "Lower KS2 foundations" },
  { id: "year-4", label: "Year 4", shortLabel: "Y4", keyStage: "KS2", ages: "Age 8–9", hasExamBoards: false, order: 4, blurb: "Lower KS2 fluency" },
  { id: "year-5", label: "Year 5", shortLabel: "Y5", keyStage: "KS2", ages: "Age 9–10", hasExamBoards: false, order: 5, blurb: "Upper KS2" },
  { id: "year-6", label: "Year 6", shortLabel: "Y6", keyStage: "KS2", ages: "Age 10–11", hasExamBoards: false, order: 6, blurb: "SATs preparation" },
  { id: "year-7", label: "Year 7", shortLabel: "Y7", keyStage: "KS3", ages: "Age 11–12", hasExamBoards: false, order: 7, blurb: "KS3 transition" },
  { id: "year-8", label: "Year 8", shortLabel: "Y8", keyStage: "KS3", ages: "Age 12–13", hasExamBoards: false, order: 8, blurb: "KS3 deepening" },
  { id: "year-9", label: "Year 9", shortLabel: "Y9", keyStage: "KS3", ages: "Age 13–14", hasExamBoards: false, order: 9, blurb: "GCSE bridging" },
  { id: "gcse", label: "GCSE", shortLabel: "GCSE", keyStage: "KS4", ages: "Age 14–16", hasExamBoards: true, order: 10, blurb: "Years 10–11 · exam-board aligned" },
  { id: "a-level", label: "A-Level", shortLabel: "A-Level", keyStage: "KS5", ages: "Age 16–18", hasExamBoards: true, order: 11, blurb: "Years 12–13 · exam-board aligned" },
];

// ── Subjects ────────────────────────────────────────────────────────────────

export const SUBJECTS: CurriculumSubject[] = [
  { id: "maths", name: "Maths", emoji: "🔢", color: "indigo" },
  { id: "english", name: "English", emoji: "📖", color: "rose" },
  { id: "science", name: "Science", emoji: "🔬", color: "emerald" },
];

// ── Exam boards per stage + subject ───────────────────────────────────────────

const GCSE_BOARDS: Record<CurriculumSubjectId, ExamBoardId[]> = {
  maths: ["AQA", "Edexcel", "OCR", "WJEC"],
  english: ["AQA", "Edexcel", "OCR", "Eduqas"],
  science: ["AQA", "Edexcel", "OCR"],
};

const A_LEVEL_BOARDS: Record<CurriculumSubjectId, ExamBoardId[]> = {
  maths: ["AQA", "Edexcel", "OCR"],
  english: ["AQA", "Edexcel", "OCR", "Eduqas"],
  science: ["AQA", "Edexcel", "OCR"],
};

export function getBoardsFor(stageId: CurriculumStageId, subjectId: CurriculumSubjectId): ExamBoardId[] {
  if (stageId === "gcse") return GCSE_BOARDS[subjectId];
  if (stageId === "a-level") return A_LEVEL_BOARDS[subjectId];
  return [];
}

// ── Build the full topic registry from the seeds ──────────────────────────────

function slug(input: string): string {
  return input
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildTopics(subjectId: CurriculumSubjectId, seeds: SubjectSeeds): CurriculumTopic[] {
  const topics: CurriculumTopic[] = [];
  const used = new Set<string>();
  for (const stage of STAGES) {
    const stageSeeds = seeds[stage.id];
    if (!stageSeeds) continue;
    for (const seed of stageSeeds) {
      const base = `${stage.id}-${subjectId}-${slug(seed.name)}`;
      let id = base;
      let n = 2;
      while (used.has(id)) {
        id = `${base}-${n++}`;
      }
      used.add(id);
      topics.push({
        id,
        stageId: stage.id,
        subjectId,
        strand: seed.strand,
        name: seed.name,
        subtopics: seed.subtopics,
        examBoards: seed.examBoards,
      });
    }
  }
  return topics;
}

export const CURRICULUM: CurriculumTopic[] = [
  ...buildTopics("maths", MATHS_SEEDS),
  ...buildTopics("english", ENGLISH_SEEDS),
  ...buildTopics("science", SCIENCE_SEEDS),
];

const TOPIC_BY_ID = new Map(CURRICULUM.map((t) => [t.id, t]));

// ── Public helpers ────────────────────────────────────────────────────────────

export function getStages(): CurriculumStage[] {
  return STAGES;
}

export function getStage(stageId: CurriculumStageId): CurriculumStage | undefined {
  return STAGES.find((s) => s.id === stageId);
}

export function getSubjects(): CurriculumSubject[] {
  return SUBJECTS;
}

export function getSubject(subjectId: CurriculumSubjectId): CurriculumSubject | undefined {
  return SUBJECTS.find((s) => s.id === subjectId);
}

export function stageHasBoards(stageId: CurriculumStageId): boolean {
  return getStage(stageId)?.hasExamBoards ?? false;
}

/** Which subjects have any content at a given stage. */
export function getSubjectsForStage(stageId: CurriculumStageId): CurriculumSubject[] {
  return SUBJECTS.filter((s) => CURRICULUM.some((t) => t.stageId === stageId && t.subjectId === s.id));
}

/**
 * Topics for a stage + subject, optionally filtered to a board. Topics without
 * an explicit examBoards list apply to every board for that stage.
 */
export function getTopics(
  stageId: CurriculumStageId,
  subjectId: CurriculumSubjectId,
  board?: ExamBoardId | null,
): CurriculumTopic[] {
  return CURRICULUM.filter((t) => {
    if (t.stageId !== stageId || t.subjectId !== subjectId) return false;
    if (!board || !t.examBoards) return true;
    return t.examBoards.includes(board);
  });
}

/** Group a stage+subject's topics by strand, preserving first-seen order. */
export function getTopicsByStrand(
  stageId: CurriculumStageId,
  subjectId: CurriculumSubjectId,
  board?: ExamBoardId | null,
): { strand: string; topics: CurriculumTopic[] }[] {
  const groups: { strand: string; topics: CurriculumTopic[] }[] = [];
  for (const topic of getTopics(stageId, subjectId, board)) {
    let group = groups.find((g) => g.strand === topic.strand);
    if (!group) {
      group = { strand: topic.strand, topics: [] };
      groups.push(group);
    }
    group.topics.push(topic);
  }
  return groups;
}

export function getTopicById(topicId: string): CurriculumTopic | undefined {
  return TOPIC_BY_ID.get(topicId);
}

export function topicCount(stageId: CurriculumStageId, subjectId: CurriculumSubjectId): number {
  return getTopics(stageId, subjectId).length;
}
