import { Subject } from "@/types";

export const SUBJECTS: Subject[] = [
  {
    id: "maths",
    name: "Mathematics",
    icon: "📐",
    color: "from-blue-500 to-indigo-600",
    level: ["GCSE", "A-Level"],
    topics: [
      // ── Domain 1: Number ────────────────────────────────────────────
      {
        id: "number",
        subject_id: "maths",
        name: "Number",
        subtopics: [
          "Fractions",
          "Decimals",
          "Percentages",
          "BIDMAS",
          "Powers and roots",
          "Standard form",
          "Factors and multiples",
          "HCF and LCM",
          "Prime factorisation",
          "Rounding and estimation",
          "Bounds",
          "Surds",
        ],
        higherOnly: ["Bounds", "Surds"],
      },
      // ── Domain 2: Algebra ───────────────────────────────────────────
      {
        id: "algebra",
        subject_id: "maths",
        name: "Algebra",
        subtopics: [
          "Expressions and simplifying",
          "Expanding brackets",
          "Factorising",
          "Solving equations",
          "Inequalities",
          "Sequences",
          "Straight line graphs",
          "Quadratic and cubic graphs",
          "Quadratics",
          "Simultaneous equations",
          "Functions",
          "Algebraic fractions",
          "Completing the square",
          "The quadratic formula",
        ],
        higherOnly: [
          "Quadratic and cubic graphs",
          "Functions",
          "Algebraic fractions",
          "Completing the square",
          "The quadratic formula",
        ],
      },
      // ── Domain 3: Ratio, Proportion & Rates of Change ───────────────
      {
        id: "ratio",
        subject_id: "maths",
        name: "Ratio, Proportion & Rates of Change",
        subtopics: [
          "Ratio",
          "Sharing in a ratio",
          "Direct proportion",
          "Inverse proportion",
          "Scale factors",
          "Speed, distance, time",
          "Density and pressure",
          "Compound measures",
        ],
        higherOnly: ["Inverse proportion", "Density and pressure", "Compound measures"],
      },
      // ── Domain 4: Geometry & Measures ───────────────────────────────
      {
        id: "geometry",
        subject_id: "maths",
        name: "Geometry & Measures",
        subtopics: [
          "Angles",
          "Polygons",
          "Circle theorems",
          "Pythagoras' theorem",
          "Trigonometry (SOH CAH TOA)",
          "Area and perimeter",
          "Volume",
          "Transformations",
          "Bearings",
          "Loci and constructions",
          "Vectors",
          "Similarity and congruence",
        ],
        higherOnly: ["Circle theorems", "Vectors", "Similarity and congruence"],
      },
      // ── Domain 5: Probability ───────────────────────────────────────
      {
        id: "probability",
        subject_id: "maths",
        name: "Probability",
        subtopics: [
          "Probability scale",
          "Tree diagrams",
          "Venn diagrams",
          "Conditional probability",
          "Relative frequency",
        ],
        higherOnly: ["Conditional probability"],
      },
      // ── Domain 6: Statistics ────────────────────────────────────────
      {
        id: "statistics",
        subject_id: "maths",
        name: "Statistics",
        subtopics: [
          "Averages (mean, median, mode)",
          "Histograms",
          "Box plots",
          "Scatter graphs",
          "Cumulative frequency",
          "Sampling",
        ],
        higherOnly: ["Histograms", "Cumulative frequency"],
      },
      // ── Calculus (A-Level only) ─────────────────────────────────────
      {
        id: "calculus",
        subject_id: "maths",
        name: "Calculus (A-Level)",
        subtopics: [
          "Differentiation from first principles",
          "Product rule",
          "Chain rule",
          "Quotient rule",
          "Integration",
          "Integration by parts",
        ],
      },
    ],
  },
  {
    id: "physics",
    name: "Physics",
    icon: "⚡",
    color: "from-purple-500 to-pink-600",
    level: ["GCSE", "A-Level"],
    topics: [
      {
        id: "mechanics",
        subject_id: "physics",
        name: "Mechanics",
        subtopics: [
          "Speed, velocity, acceleration",
          "Newton's laws",
          "SUVAT equations",
          "Momentum",
          "Work, energy, power",
          "Forces and free body diagrams",
        ],
      },
      {
        id: "electricity",
        subject_id: "physics",
        name: "Electricity",
        subtopics: [
          "Ohm's law",
          "Series and parallel circuits",
          "Resistance and resistivity",
          "Kirchhoff's laws",
          "EMF and internal resistance",
        ],
      },
      {
        id: "waves",
        subject_id: "physics",
        name: "Waves",
        subtopics: [
          "Frequency, wavelength, speed",
          "Transverse vs longitudinal",
          "Reflection and refraction",
          "Diffraction",
          "The electromagnetic spectrum",
        ],
      },
    ],
  },
  {
    id: "chemistry",
    name: "Chemistry",
    icon: "🧪",
    color: "from-green-500 to-emerald-600",
    level: ["GCSE", "A-Level"],
    topics: [
      {
        id: "atomic-structure",
        subject_id: "chemistry",
        name: "Atomic Structure",
        subtopics: [
          "Protons, neutrons, electrons",
          "Isotopes",
          "Electronic configuration",
          "The periodic table",
        ],
      },
      {
        id: "bonding",
        subject_id: "chemistry",
        name: "Bonding",
        subtopics: [
          "Ionic bonding",
          "Covalent bonding",
          "Metallic bonding",
          "Intermolecular forces",
        ],
      },
      {
        id: "calculations",
        subject_id: "chemistry",
        name: "Calculations",
        subtopics: [
          "Moles",
          "Empirical and molecular formulae",
          "Concentration calculations",
          "Percentage yield",
          "Atom economy",
        ],
      },
    ],
  },
  {
    id: "biology",
    name: "Biology",
    icon: "🧬",
    color: "from-teal-500 to-cyan-600",
    level: ["GCSE", "A-Level"],
    topics: [
      {
        id: "cells",
        subject_id: "biology",
        name: "Cell Biology",
        subtopics: [
          "Cell structure",
          "Mitosis and meiosis",
          "DNA and protein synthesis",
          "Diffusion and osmosis",
        ],
      },
      {
        id: "genetics",
        subject_id: "biology",
        name: "Genetics & Evolution",
        subtopics: [
          "Inheritance and Punnett squares",
          "Mutations",
          "Natural selection",
          "Genetic engineering",
        ],
      },
    ],
  },
];
