import { Subject } from "@/types";

export const SUBJECTS: Subject[] = [
  {
    id: "maths",
    name: "Mathematics",
    icon: "📐",
    color: "from-blue-500 to-indigo-600",
    level: ["GCSE", "A-Level"],
    topics: [
      {
        id: "algebra",
        subject_id: "maths",
        name: "Algebra",
        subtopics: [
          "Solving linear equations",
          "Expanding brackets",
          "Factorising quadratics",
          "Simultaneous equations",
          "Inequalities",
          "Algebraic fractions",
          "Completing the square",
          "The quadratic formula",
        ],
      },
      {
        id: "number",
        subject_id: "maths",
        name: "Number",
        subtopics: [
          "Fractions, decimals, percentages",
          "Ratio and proportion",
          "Standard form",
          "Indices and surds",
          "HCF and LCM",
          "Prime factorisation",
        ],
      },
      {
        id: "geometry",
        subject_id: "maths",
        name: "Geometry & Measures",
        subtopics: [
          "Area and perimeter",
          "Circle theorems",
          "Pythagoras theorem",
          "Trigonometry (SOH CAH TOA)",
          "Vectors",
          "Transformations",
          "Angles in polygons",
        ],
      },
      {
        id: "statistics",
        subject_id: "maths",
        name: "Statistics & Probability",
        subtopics: [
          "Mean, median, mode",
          "Probability trees",
          "Venn diagrams",
          "Histograms",
          "Cumulative frequency",
          "Box plots",
        ],
      },
      {
        id: "calculus",
        subject_id: "maths",
        name: "Calculus (A-Level)",
        subtopics: [
          "Differentiation from first principles",
          "Product rule",
          "Chain rule",
          "Quotient rule",
          "Integration",
          "Integration by parts",
        ],
      },
    ],
  },
  {
    id: "physics",
    name: "Physics",
    icon: "⚡",
    color: "from-purple-500 to-pink-600",
    level: ["GCSE", "A-Level"],
    topics: [
      {
        id: "mechanics",
        subject_id: "physics",
        name: "Mechanics",
        subtopics: [
          "Speed, velocity, acceleration",
          "Newton's laws",
          "SUVAT equations",
          "Momentum",
          "Work, energy, power",
          "Forces and free body diagrams",
        ],
      },
      {
        id: "electricity",
        subject_id: "physics",
        name: "Electricity",
        subtopics: [
          "Ohm's law",
          "Series and parallel circuits",
          "Resistance and resistivity",
          "Kirchhoff's laws",
          "EMF and internal resistance",
        ],
      },
      {
        id: "waves",
        subject_id: "physics",
        name: "Waves",
        subtopics: [
          "Frequency, wavelength, speed",
          "Transverse vs longitudinal",
          "Reflection and refraction",
          "Diffraction",
          "The electromagnetic spectrum",
        ],
      },
    ],
  },
  {
    id: "chemistry",
    name: "Chemistry",
    icon: "🧪",
    color: "from-green-500 to-emerald-600",
    level: ["GCSE", "A-Level"],
    topics: [
      {
        id: "atomic-structure",
        subject_id: "chemistry",
        name: "Atomic Structure",
        subtopics: [
          "Protons, neutrons, electrons",
          "Isotopes",
          "Electronic configuration",
          "The periodic table",
        ],
      },
      {
        id: "bonding",
        subject_id: "chemistry",
        name: "Bonding",
        subtopics: [
          "Ionic bonding",
          "Covalent bonding",
          "Metallic bonding",
          "Intermolecular forces",
        ],
      },
      {
        id: "calculations",
        subject_id: "chemistry",
        name: "Calculations",
        subtopics: [
          "Moles",
          "Empirical and molecular formulae",
          "Concentration calculations",
          "Percentage yield",
          "Atom economy",
        ],
      },
    ],
  },
  {
    id: "biology",
    name: "Biology",
    icon: "🧬",
    color: "from-teal-500 to-cyan-600",
    level: ["GCSE", "A-Level"],
    topics: [
      {
        id: "cells",
        subject_id: "biology",
        name: "Cell Biology",
        subtopics: [
          "Cell structure",
          "Mitosis and meiosis",
          "DNA and protein synthesis",
          "Diffusion and osmosis",
        ],
      },
      {
        id: "genetics",
        subject_id: "biology",
        name: "Genetics & Evolution",
        subtopics: [
          "Inheritance and Punnett squares",
          "Mutations",
          "Natural selection",
          "Genetic engineering",
        ],
      },
    ],
  },
];
