"use client";

import Link from "next/link";
import PortalShell from "@/components/portal/PortalShell";
import {
  getStages,
  getSubjects,
  topicCount,
  curriculumStats,
  type ScienceTrack,
} from "@/lib/curriculum";

function CoverageGrid() {
  const stages = getStages();
  const subjects = getSubjects();
  const stats = curriculumStats();

  return (
    <main className="max-w-5xl mx-auto px-4 sm:px-6 py-8">
      <Link href="/portal/teach" className="text-sm text-indigo-600 hover:text-indigo-800 font-medium">
        ← Back to Teach
      </Link>
      <h1 className="text-2xl font-bold text-gray-900 mt-3 mb-1">Curriculum coverage</h1>
      <p className="text-gray-500 text-sm mb-2">
        {stats.totalTopics} teachable topics across Maths, English and Science (Year 3 → A-Level).
      </p>
      <p className="text-gray-400 text-xs mb-8">
        Every topic includes sub-objectives. Lessons and worksheets are generated by AI on demand.
      </p>

      <div className="overflow-x-auto rounded-2xl border border-gray-200 bg-white">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-gray-100 bg-gray-50">
              <th className="text-left px-4 py-3 font-semibold text-gray-700">Year</th>
              {subjects.map((s) => (
                <th key={s.id} className="text-center px-4 py-3 font-semibold text-gray-700">
                  {s.emoji} {s.name}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {stages.map((stage) => (
              <tr key={stage.id} className="border-b border-gray-50 last:border-0">
                <td className="px-4 py-3 font-medium text-gray-900">
                  {stage.label}
                  <span className="block text-xs text-gray-400 font-normal">{stage.keyStage}</span>
                </td>
                {subjects.map((sub) => {
                  const n =
                    stage.id === "gcse" && sub.id === "science"
                      ? topicCount(stage.id, sub.id, { scienceTrack: "combined" }) +
                        topicCount(stage.id, sub.id, { scienceTrack: "triple" })
                      : topicCount(stage.id, sub.id);
                  return (
                    <td key={sub.id} className="text-center px-4 py-3 text-gray-700">
                      {n}
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-8 grid sm:grid-cols-2 gap-4">
        <div className="rounded-2xl border border-gray-200 bg-white p-5">
          <h2 className="font-semibold text-gray-900 mb-2">GCSE Science routes</h2>
          <ul className="text-sm text-gray-600 space-y-1">
            <li>Combined Science: {topicCount("gcse", "science", { scienceTrack: "combined" as ScienceTrack })} topics</li>
            <li>Triple Science: {topicCount("gcse", "science", { scienceTrack: "triple" as ScienceTrack })} topics</li>
          </ul>
        </div>
        <div className="rounded-2xl border border-gray-200 bg-white p-5">
          <h2 className="font-semibold text-gray-900 mb-2">GCSE Maths</h2>
          <p className="text-sm text-gray-600">
            Board-aligned topics for AQA, Edexcel and OCR with Foundation / Higher tier filtering.
          </p>
        </div>
      </div>
    </main>
  );
}

export default function CurriculumCoveragePage() {
  return <PortalShell>{() => <CoverageGrid />}</PortalShell>;
}
